69 create haski contact page
HASKI-RAK/HASKI-Frontend pull request #143
Opened 2023-03-30 12:31 UTC by Platura

## Description

Added a contact form that allows the user to write a report and send it. Only a description is required and selection of the reoprttype and topic is optional.

## Type of changes

Added a contact page.

- [ ] Feature

2023-03-30 13:20 UTC, DimitriB01 commented
2 tests schlagen fehl.

2023-03-31 09:29 UTC, theUpsider commented
Und merge Konflikte ^^

2023-03-31 12:49 UTC, DimitriB01 commented on package.json
> +
Extra?

2023-03-31 12:49 UTC, DimitriB01 commented on src/components/Form/Contactform.tsx
> +  const handleInputChange = (e: any) => {
Hier ein definierter Typ möglich und nicht any?

2023-03-31 12:49 UTC, DimitriB01 commented on src/components/Form/Contactform.tsx
> +  const handleSubmit = (event: any) => {
Hier ein definierter Typ möglich und nicht any?

2023-03-31 12:49 UTC, DimitriB01 commented on src/components/Form/Contactform.tsx
> +        sx={{ minWidth: 120, backgroundColor: "white" }}
hier womöglich auf theme.palette.primary.main verweisen

2023-03-31 12:49 UTC, DimitriB01 commented on src/components/Form/Contactform.tsx
> +        sx={{ minWidth: 120, backgroundColor: "white" }}
ein Beispiel ist in meinem Branch

2023-03-31 12:49 UTC, DimitriB01 commented on src/components/Form/Contactform.tsx
> +              <MenuItem value={"le"} >{ t("components.contactform.learningelement")}</MenuItem>
eigentlich wäre hier der translation name: components.form.contactform.learningelement.... 
kommt ein paar mal vor

2023-03-31 12:49 UTC, DimitriB01 commented on src/shared/translation/translationEnglish.json
> +	"pages.contact.title": "Contact",
eigentlich "pages.Contact.Contact.title" weil es ja in dem file ist

2023-03-31 13:07 UTC, theUpsider commented on yarn.lock
> +  version "22.4.13"
die yarn lock am besten nicht commiten. muss ich noch zu gitignore hinzufügen

2023-04-02 15:11 UTC, juli-txt commented on src/components/Form/Contactform.tsx
> +    if (contactValues.description == "") {
Noch besser wäre vielleicht `!!contactValues.description`. Das wandelt `contactValues.description` in einen Boolean um. 
https://medium.com/@chirag.viradiya_30404/whats-the-double-exclamation-sign-for-in-javascript-d93ed5ad8491

2023-04-04 10:37 UTC, Platura commented on src/components/Form/Contactform.tsx
> +  const handleInputChange = (e: any) => {
Nicht schön aber geht

2023-04-05 12:43 UTC, Platura commented on src/components/Form/Contactform.tsx
> +export const Contactform = ( {width, sendtoBackend}: ContactformParameter) => {
Tests sind wieder kaputt T.T. Wurde aber ausgelagert

2023-04-05 15:35 UTC, juli-txt commented on src/components/Form/Contactform.tsx
> +export const Contactform = ( {width, sendtoBackend}: ContactformParameter) => {
Könntest du die Komponenten, Dateien und den Ordner bitte noch zu "ContactForm" ändern. 

Komponenten sollten als default und nicht direkt exportiert werden.

2023-04-17 08:27 UTC, theUpsider requested changes

2023-05-05 09:27 UTC, juli-txt commented on src/pages/App/App.tsx
> +import { HaskiTheme, Theme } from "@utils";
Code smell. Theme bitte entfernen.

2023-05-05 09:27 UTC, juli-txt commented on src/pages/Contact/Contact.test.tsx
> +  expect(submit).toBeCalled();
Wir testen nicht mehr mit Snapshots, daher diese bitte entfernen.

2023-05-05 09:28 UTC, juli-txt commented on src/pages/Contact/__snapshots__/Contact.test.tsx.snap
> +// Jest Snapshot v1, https://goo.gl/fbAQLP
Bitte entfernen.

2023-05-05 09:31 UTC, juli-txt commented on src/pages/Contact/Contact.tsx
> +  const {onSubmit=submit}=props;
Pls use (https://marketplace.visualstudio.com/items?itemName=rvest.vs-code-prettier-eslint)

2023-05-05 09:38 UTC, juli-txt commented on src/shared/translation/translationGerman.json
> +  "components.ContactForm.topic": "Thema",
Sowas könnte auch als allgemeiner Eintrag verwendet werden. Da dieser sicherlich einige Male benötigt wird. Bsp: "topic": "Thema"

2023-05-05 09:40 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "components.ContactForm.topic": "Topic",
Hier das gleiche Spiel wie im Englischen

2023-05-05 09:45 UTC, juli-txt commented on src/pages/Contact/Contact.tsx
> +export const Contact = ({useContact = _useContact, ...props}: ContactProps) => {
Der Konsistenz nach ist ein named export hier nicht von Nöten. Siehe Komponenten Guidelines

2023-05-05 09:49 UTC, juli-txt commented on src/pages/Contact/Contact.test.tsx
> +import { fireEvent } from "@testing-library/react";
Imports der testing-library bitte zu einem zusammenfassen.

2023-05-05 09:50 UTC, juli-txt commented on src/pages/Contact/Contact.test.tsx
> +import renderer, {act} from "react-test-renderer";
act kann auch mit "@testing-library/react" importiert werden. renderer ist ohne die Snapshots nicht mehr nötig

2023-05-05 09:54 UTC, juli-txt commented on src/pages/Contact/Contact.test.tsx
> +test("renders correctly and matches snapshot", () => {
Ein alle Tests umfassendes describe(() => {}) wäre noch nett, da somit bei einem Testdurchgang nicht nur ein einzelner Test failed sondern die komplette Test Suite und Herkunft des Fails leichter aufgespührt werden kann.

2023-05-05 09:56 UTC, juli-txt commented on src/components/ContactForm/ContactForm.hooks.tsx
> +        const { defaultReportType = "other", defaultReportTopic = "", defaultDescription = "" } = params || {};
Hier bitte ebenfalls den Code Smell beheben

2023-05-05 09:57 UTC, juli-txt commented on src/components/ContactForm/ContactForm.test.tsx
> +test("Test default params", () => {
Die gleichen Punkte wie bei den anderen Test gelten hier auch

2023-05-05 09:58 UTC, juli-txt commented on src/components/ContactForm/ContactForm.tsx
> +  onsendtoBackend?: () => void;
Vielleicht eher onSendToBackend?

2023-05-05 09:59 UTC, juli-txt commented on src/components/ContactForm/ContactForm.tsx
> +  onsendtoBackend?: () => void;
Allgemein sind in der Datei hier einige namings die dem camelCase widersprechen

2023-05-05 10:00 UTC, juli-txt commented on src/components/ContactForm/ContactForm.tsx
> +export const ContactForm = ({
Kein named export von Nöten

2023-05-10 16:42 UTC, theUpsider requested changes
siehe kommentare

2023-05-10 16:42 UTC, theUpsider commented on src/common/components/DefaultTextField/DefaultTextField.tsx
> +export { TextField as DefaultTextField } from "@mui/material";
Wieso plötzlich rückganing? führ mal `yarn lint` aus nochmal^^

2023-05-10 16:42 UTC, theUpsider commented on src/common/components/index.ts
> +
Hier auch nochmal linten. Wir nutzen einfache ' statt "

2023-05-10 16:42 UTC, theUpsider commented on src/common/services/index.ts
> +
lint auch

2023-05-10 16:42 UTC, theUpsider commented on src/components/ContactForm/ContactForm.hooks.tsx
> +export type useContactFormHookParams = {
noch dokumentation hinzufügen.

2023-05-10 16:42 UTC, theUpsider commented on src/components/ContactForm/ContactForm.hooks.tsx
> +export const useContactForm = (
doku

2023-05-10 16:42 UTC, theUpsider commented on src/components/ContactForm/ContactForm.tsx
> +const ContactForm = ({
doku

2023-05-10 16:42 UTC, theUpsider commented on src/components/ContactForm/ContactForm.tsx
> +export type ContactFormProps = {
doku

2023-05-10 16:42 UTC, theUpsider commented on src/pages/Contact/Contact.tsx
> +};
Die Props nutzt du nirgends, da es eine Page ist. Kannst eig komplett entfernen.

2023-05-10 16:42 UTC, theUpsider commented on src/pages/Contact/Contact.tsx
> +};
```suggestion

export const Contact = ({useContact = _useContact}: ContactProps) => {
  const { handleSubmit } = useContact();
  return <ContactForm onSubmit={handleSubmit} />
};
export default Contact;

```

2023-05-10 16:42 UTC, theUpsider commented on src/pages/Contact/Contact.test.tsx
> +import renderer from "react-test-renderer";
unnötiger import

2023-05-10 16:42 UTC, theUpsider commented on src/pages/Contact/Contact.hooks.tsx
> +export const useContact = (): ContactHookReturn => {
kannst ganzes file löschen

2023-05-10 16:42 UTC, theUpsider commented on src/pages/Home/Home.tsx
>      <div>
```suggestion
    <>
```

2023-05-22 10:05 UTC, theUpsider requested changes
Ich weiß du bist vermutlich mitten im development, hab aber paar anmerkungen geschrieben. Dachte erst das sei der finale Stand XD deshalb nimms nicht all zu genau, wenn du eh noch am entwickeln bist.

2023-05-22 10:05 UTC, theUpsider commented on src/components/ContactForm/ContactForm.tsx
> +  onSubmit?: (formdata: any) => void
Hier müssten die Paramater von der useContact rein

2023-05-25 13:08 UTC, theUpsider commented on src/pages/Contact/Contact.hooks.tsx
> + * Hook for the Contact page logic which handles the sending of the responsebody to the backend.
Bitte noch die Daten von der ContactForm über den submithandler hier reinprügeln

2023-06-01 12:28 UTC, theUpsider approved these changes

2023-06-13 13:24 UTC, theUpsider commented on .env.development
> +BACKEND="http://localhost:5000"
Jo das brauchen wir auf fakedomain ^^
```suggestion
BACKEND="http://fakedomain.com:5000"
```

2023-06-13 13:24 UTC, theUpsider commented on .unimportedrc.json
> +  ],
Jo wo kommt das her?

2023-06-13 13:24 UTC, theUpsider commented on src/pages/Contact/Contact.hooks.tsx
> +          })
```suggestion
        .catch((error) => {
          setIsLoading(false)
          addSnackbar({
            message: t('pages.Contact.error') + error,
            severity: 'error'
          })
```

2023-06-13 13:24 UTC, theUpsider commented on src/common/services/contact/postContactForm.ts
> +  const user_id = 2
Hab neues issue für nächsten sprint wo wir die nutzer id aus sclice verwenden können: https://github.com/HASKI-RAK/HASKI-Frontend/issues/181

2023-06-14 09:22 UTC, merged