98 create snackbar messages
HASKI-RAK/HASKI-Frontend pull request #156
Opened 2023-05-09 12:42 UTC by juli-txt

## Description

- Added snackbar messages
- Added network status service
- Added example implementation of snackbar usage when internet connection is lost or regained 

## Type of changes

- [ ] Bugfix 
- [x] Feature 
- [ ] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other

2023-05-10 12:54 UTC, DimitriB01 commented on src/common/services/SnackbarProvider/SnackbarProvider.hooks.tsx
> +      if (newSnackbar.severity === 'error' || newSnackbar.severity === 'warning') {
const { severity, message } = newSnackbar 
macht das anschließende lesen einfacher mmn

2023-05-10 12:54 UTC, DimitriB01 commented on src/common/services/SnackbarProvider/SnackbarProvider.hooks.tsx
> +  const updateSnackbar = useCallback((snackbarToUpdate: SnackbarMessageProps) => {
das selbe wie oben

2023-05-10 12:54 UTC, DimitriB01 commented on src/common/services/SnackbarProvider/SnackbarProvider.hooks.tsx
> +    if (snackbarToRemove.severity === 'error' || snackbarToRemove.severity === 'warning') {
same

2023-05-10 12:54 UTC, DimitriB01 commented on src/components/SnackbarContainer/SnackbarContainer.tsx
> +  const [recentlyOffline, setRecentlyOffline] = useState(false)
useState<boolean>(false)

2023-05-10 12:54 UTC, DimitriB01 commented on src/components/SnackbarMessage/SnackbarMessage.tsx
> +  const [openTransition, setOpenTransition] = useState(true)
useState (true) mit mit <> boolean

2023-05-10 12:54 UTC, DimitriB01 commented on src/components/SnackbarContainer/SnackbarContainer.tsx
> +  const [recentlyOffline, setRecentlyOffline] = useState(false)
mit <> boolean

2023-05-10 12:54 UTC, DimitriB01 commented on src/pages/App/App.tsx
> +              <Route path="/🥚" element={<div>Ei</div>} />
Was für Ei

2023-05-10 16:04 UTC, theUpsider requested changes
Stuff that was discussed

2023-05-10 16:04 UTC, theUpsider commented on src/pages/App/App.tsx
> +              <Route path="/🥚" element={<div>Ei</div>} />
Easter egg bruder

2023-05-15 14:12 UTC, theUpsider approved these changes

2023-05-15 14:16 UTC, merged