Home page refactored
HASKI-RAK/HASKI-Frontend pull request #192
Opened 2023-07-20 13:55 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [ ] Feature 
- [x] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [x] Everything build out of Material UI components
- [x] New Material UI components capsulated via dependency injection in "@common/components"
- [x] Provide basic information pieces in comments
- [x] Establish interface to backend (if necessary) 
- [x] Use Skeleton components if something has to be fetched (if necessary)
- [x] Error management: Components should handle undefined inputs
- [x] Components should be resuable (if possible)
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-07-20 13:55 UTC, DimitriB01 commented
1 test schläft fehl, der wird in einem anderen Branch (Betrifft fetchen von Couse-Topics) gefixt

2023-07-20 15:09 UTC, theUpsider requested changes
Kommentare anbei^^

2023-07-20 15:09 UTC, theUpsider commented on src/pages/Home/Home.test.tsx
> +    const addSnackbarMock = jest.fn()
Mit dem mock machst du nix. Könnte man löschen bzw drauf testen.

2023-07-20 15:09 UTC, theUpsider commented on src/pages/Home/Home.tsx
>  import { useNavigate } from 'react-router-dom'
import { DefaultButton as Button, DefaultStack as Stack } from '@common/components' statt Mui import

2023-07-21 07:00 UTC, DimitriB01 commented on src/common/core/Course/Course.ts
> +type CourseResponse = {
Man benötigt courses, da es die Struktur der Antwort darstellt:

{
    "courses": [
        {
            "created_at": null,
            "created_by": null,
            "id": 1,
            "last_updated": null,
            "lms_id": 2,
            "name": "Software Engineering",
            "university": "HS-RE"
        },
        {
            "created_at": null,
            "created_by": null,
            "id": 2,
            "last_updated": null,
            "lms_id": 2,
            "name": "Software Architecture",
            "university": "HS-AS"
        }
    ]
}

2023-07-21 07:13 UTC, DimitriB01 commented on src/pages/Home/Home.tsx
> +const initialCourses: Course[] = [
true

2023-07-21 08:41 UTC, DimitriB01 commented on src/pages/Home/Home.tsx
>      }
Hier braucht man 2 catch(), für jedes then jeweils. Aber sonst passt

2023-07-21 08:47 UTC, theUpsider requested changes
Nur one small change :D

2023-07-21 08:47 UTC, theUpsider commented on src/common/services/Courses/getCourses.ts
>  import { CourseReturn } from '@core'
CourseReturn und den anderen import noch zusammenfassen. Also dass beide aus @core sind ^^

2023-07-21 09:16 UTC, merged