Course page refactored
HASKI-RAK/HASKI-Frontend pull request #193
Opened 2023-07-25 12:17 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [ ] Feature 
- [x] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [x] Everything build out of Material UI components
- [x] New Material UI components capsulated via dependency injection in "@common/components"
- [x] Provide basic information pieces in comments
- [x] Establish interface to backend (if necessary) 
- [x] Use Skeleton components if something has to be fetched (if necessary)
- [x] Error management: Components should handle undefined inputs
- [x] Components should be resuable (if possible)
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-08-04 06:51 UTC, DimitriB01 commented
login/Login.test schlägt fehl. Ist im Eval-Cleanup auch so 👎

2023-08-04 10:16 UTC, theUpsider requested changes

2023-08-04 10:16 UTC, theUpsider commented on src/components/MenuBar/MenuBar.tsx
Objekte als immutable betrachen. Und dann wird instant ein einzeiler draus.
```suggestion
  const reversedTopics: Topic[] = [...topicsPath].sort((a, b) => reversedTopics.indexOf(b) - reversedTopics.indexOf(a))

```

2023-08-04 10:16 UTC, theUpsider commented on src/components/MenuBar/MenuBar.tsx
> +  const handleOpenTopicsMenu = async (event: React.MouseEvent<HTMLElement>) => {
weiter unten wieder skeleton als in memo wrappen, weil sich der render nicht ändert

2023-08-04 10:16 UTC, theUpsider commented on src/components/MenuBar/MenuBar.tsx
> +                                  }}></Box>
```suggestion
                                  }}/>
```

2023-08-04 10:16 UTC, theUpsider commented on src/pages/Course/Course.tsx
> +import { Stack } from '@mui/system'
```suggestion
import {
  DefaultButton as Button,
  DefaultCard as Card,
  DefaultCardContent as CardContent,
  DefaultSkeleton as Skeleton,
  DefaultTypography as Typography,
  DefaultBox as Box,
  DefaultStack as Stack
} from '@common/components'
```

2023-08-04 10:16 UTC, theUpsider commented on src/pages/Course/Course.tsx
> +  }, [authcontext.isAuth])
glaube kann man entfernen, weil die Komponente eh neu rendert, sobald sich der context ändert.
```suggestion
  }, [])
```

2023-08-04 10:16 UTC, theUpsider commented on src/pages/Course/Course.tsx
> +  const skeletonItems = []
wieder als Memo. Man könnte es auch als common component auslagern, da es mehrmals in versch. komponenten benötigt wird.

2023-08-04 10:16 UTC, theUpsider commented on src/pages/Home/Home.tsx
>      }
authcontext.isAuth könnte man enfternen, wie im anderen kommentar angemerkt.

2023-08-08 09:12 UTC, theUpsider requested changes

2023-08-08 09:12 UTC, theUpsider commented on src/components/LocalNav/LazyLoadingLearningPathElement.tsx
> +  if (loadingElements) {
Auslagern überall (wie in discord besprochen)

2023-08-08 09:12 UTC, theUpsider commented on src/components/LocalNav/LocalNav.tsx
> +  const skeletonItems = useMemo(() => {
hier die ausgelagerte komponente nutzen dann :)

2023-08-08 09:12 UTC, theUpsider commented on src/components/MenuBar/MenuBar.test.tsx
> +import React from 'react'
unused variable. immer yarn lint laufen lassen^^

2023-08-08 09:12 UTC, theUpsider commented on src/components/MenuBar/MenuBar.tsx
> +  const skeletonItems = useMemo(() => {
Hier dann auch die ausgelagerte Komponente nutzen

2023-08-08 09:12 UTC, theUpsider commented on src/pages/Course/Course.tsx
> +  const skeletonItems = useMemo(() => {
Hier auch

2023-08-14 17:14 UTC, merged