195 user has to accept privacy policy before he logs in
HASKI-RAK/HASKI-Frontend pull request #213
Opened 2023-10-04 12:41 UTC by Platura

## Description

## Type of changes

- [ ] Bugfix 
- [ ] Feature 
- [ ] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-10-05 10:10 UTC, juli-txt commented on package.json
> +    "react-cookie": "^6.1.1",
Die Bibliothek bitte [hier](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/616264?filePath=%2FHASKI-Extern%2F02-Software%2F02-Deployment%2FLizenzsammlung.xlsx) hinzufügen und alle Felder dazu ausfüllen.

2023-10-05 10:17 UTC, juli-txt commented on src/components/index.ts
> +export {default as PrivacyModal} from './PrivacyModal/PrivacyModal'
prettier

2023-10-05 10:20 UTC, juli-txt commented on src/pages/App/App.tsx
> +      <SnackbarProvider>
```suggestion
    <SnackbarProvider>
        <AuthProvider>
```

2023-10-05 10:20 UTC, juli-txt commented on src/pages/App/App.tsx
> +    </AuthProvider>
```suggestion
        </AuthProvider>
    </SnackbarProvider>
```

2023-10-05 10:47 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "components.PrivacyModal.declined": "Data is not being collected. Should you change your mind look in the settings."
Der erste Teil ergibt für mich zeitlich keinen Sinn, da der Satz nur aussagt, dass im aktuellen Moment keine Daten gesammelt werden.

```suggestion
  "components.PrivacyModal.declined": "Data will not be collected. Should you change your mind, look in the settings."
```

2023-10-05 10:50 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "components.PrivacyModal.TermsofService": "Terms of service and Privacy Policy",
```suggestion
  "components.PrivacyModal.termsOfService": "Terms of service and privacy policy",
```

2023-10-05 10:59 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +//was passiert wenn accept geklickt wird?
Für zukünftige ToDos bitte im GitHub Technical oder User Story Issues anlegen und ausformulieren.
Diese je nach Wichtigkeit im Backlog oder in der Icebox platzieren.

```suggestion
```

2023-10-05 11:00 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +
```suggestion
/**
 * prop usePrivacyModal - Hook used for the Modal logic upon clicking a button.
 * @interface
 */
```

2023-10-05 11:09 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +import React from 'react'
Sollte nicht nötig sein.

```suggestion
```

2023-10-05 11:10 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +  const [checked, setCheck] = React.useState(false)
```suggestion
  const [open, setOpen] = useState(true)
  const [checked, setCheck] = useState(false)
```

2023-10-05 11:11 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +  )
Für die bessere Übersicht.

```suggestion
  //Disable backdropClick so the Modal only closes via the buttons
  const handleClose = (event: React.MouseEvent<HTMLElement>, reason: string) => {
    if (reason && reason == 'backdropClick') return
  }

  //setting the check so the button gets enabled
  const handleChecked = (event: React.MouseEvent<HTMLElement>) => {
    setCheck((event.target as HTMLInputElement).checked)
  }

  //close the modal and set the cookie in the hook
  const handleModal = (lol: boolean) => {
    onAcceptHandler(lol)
    setOpen(false)
  }

  //load nothing if cookie is set
  if (document.cookie.includes('privacy_accept_token')) {
    return null
  }

  //load nothing if current page is privacypolicy
  if (window.location.href.includes('privacypolicy')) {
    return null
  }
  
  return (
    <Modal
      aria-labelledby="privacy-modal"
      aria-describedby="makes-the-user-accept-the-privacypolicy-or-not"
      open={open}
      onClose={handleClose}
      closeAfterTransition>
      <Box sx={style}>
        <Typography id="transition-modal-title" variant="h4" component="h2">
          {t('components.PrivacyModal.TermsofService')}
          <Typography id="modal-text" variant="h6" component="h2">
            {t('components.PrivacyModal.afterReading')}
            <FormGroup>
              <FormControlLabel
                onClick={handleChecked}
                control={<Checkbox />}
                label={
                  <div>
                    {t('agree')}&nbsp;
                    <Link href="privacypolicy" underline="none">
                      Privacy Policy
                    </Link>
                  </div>
                }
              />
              <FormControlLabel control={<Checkbox />} label="Agree someting else" />
            </FormGroup>
          </Typography>
          <Box
            height={'20%'}
            sx={{
              display: 'flex',
              justifyContent: 'space-between'
            }}>
            <Button variant={'contained'} sx={{ alignSelf: 'end' }} onClick={() => handleModal(false)}>
              {t('decline')}
            </Button>
            <Button
              variant={'contained'}
              sx={{ alignSelf: 'end' }}
              disabled={!checked}
              onClick={() => handleModal(true)}>
              {t('accept')}
            </Button>
          </Box>
        </Typography>
      </Box>
    </Modal>
  )
```

2023-10-05 11:12 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +  const handleClose = (event: React.MouseEvent<HTMLElement>, reason: string) => {
Nicht verwendete Events als _ darstellen. Siee Komponentenguide

```suggestion
  const handleClose = (_: React.MouseEvent<HTMLElement>, reason: string) => {
```

2023-10-05 11:14 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +          {t('components.PrivacyModal.TermsofService')}
```suggestion
          {t('components.PrivacyModal.termsOfService')}
```

2023-10-05 11:18 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +  }
Ist es sinnvoll die gerenderte HTML nach dem Cookie zu überprüfen?
Wäre es möglich, dem Hook als Return den State "cookie" mitzugeben und diesen hier zu prüfen?
Meiner Meinung nach die logisch schönere Variante.

2023-10-05 11:31 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +    onAcceptHandler(lol)
```suggestion
  const handleModal = (cookieAccepted: boolean) => {
    onAcceptHandler(cookieAccepted)
```

2023-10-05 11:35 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                    </Link>
Zum Navigieren bitte react-router verwenden. Siehe Footer für Beispiel, wie man das mit Link in Einklang bringt.

2023-10-05 11:36 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                  </div>
<> wird im Gegensatz zu <div> nicht gerendert. Spart daher Performance

```suggestion
                  <>
                    {t('agree')}&nbsp;
                    <Link href="privacypolicy" underline="none">
                      Privacy Policy
                    </Link>
                  </>
```

2023-10-05 11:37 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +export default PrivacyModal
Um unnötige Rerender zu vermeiden.

```suggestion
export default memo(PrivacyModal)
```

2023-10-11 08:40 UTC, Platura commented on src/shared/translation/translationEnglish.json
> +  "components.PrivacyModal.accepted": "Thank you for your trust. Data for better learning experience is now being collected.",
Habs lustigerweise auch so in deutsch übersetzt

2023-10-27 10:03 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                  handleModal(false), (window.location.href = 'https://moodle.hs-kempten.de/enrol/index.php?id=357')
Ich hab' mal nachgeschaut und finde, dass .assign() ein bisschen besser zum Wechseln einer Webseite passt. Bei href wird die aktuelle Webseite überschrieben. Das wirkt etwas hacky.

Habe mit Dimitri gesprochen, da es irgendwie nicht so sinnvoll ist, alle Studierenden, also auch Informatiker, auf das Game Engineering SWEG Moodle zu schicken. Also auch die Aschaffenburger, wenn sie unser Frontend verwenden. Wir würden vorschlagen, die Hochschule aus dem Backend zu fetchen und dann mittels if else die User zu verschiedenen Moodles zu schicken. (Zwischen IF und GE soll nach der Evaluation aber irgendwann dennoch entschieden werden, um Studierende direkt dorthin zu schicken, wo sie herkamen) 

Die Keys der Hochschulen sind HS-KE und TH-AB
Die Links sind https://moodle.hs-kempten.de/ und https://moodle.th-ab.de/


```suggestion
                  handleModal(false)
                  window.location.assign(https://moodle.hs-kempten.de/enrol/index.php?id=357')
```

2023-10-27 10:15 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                    {t('components.PrivacyModal.readPrivacypolicy')}&nbsp;
Der non-breaking space hier hat mich etwas verwirrt.
Wäre es auch möglich das Leerzeichen in den Translation Files hinzuzufügen? Insofern es nicht irgendein gewolltes Behaviour zerstört.

2023-10-27 10:19 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                      {t('pages.PrivacyPolicy')}
Der Key muss kleingeschrieben werden, sonst funktionieren die Breadcrumps von David nicht.

2023-10-27 10:45 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> + * A Formcontrol label can be added for other documents that need to be read by the user.
Inwiefern kann ein FormControlLabel hinzugefügt werden? Sehe kein Parameter oder children, mit denen was von außen injiziert werden könnte

2023-10-27 10:49 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +  //setting the check so the button gets enabled
Sets checkbox to enable button

2023-10-27 10:57 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +    <Modal
Wenn Condition fehl schlägt wird automatisch undefined returned

```suggestion
  return (
    <>
        { // Don't load anything, if the current page is privacy policy page or the privacy policy cookie is set.
        !(currentLocation.pathname.includes('privacypolicy') || cookies['privacy_accept_token']) && (

            <Modal
```

2023-10-27 10:58 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +    </Modal>
```suggestion
            </Modal>
        }
    </>
```

2023-10-27 11:04 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "components.PrivacyModal.afterReading": "HASKI is using essential cookies. Further Information about the collected data and its usage can be found in the privacy policy:",
```suggestion
  "components.PrivacyModal.afterReading": "HASKI is using essential cookies. Further information about the collected data and its usage can be found in the privacy policy:",
```

2023-10-27 11:06 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "User fetching error": "There was an Error fetching User data",
Könnte man mal diskutieren, ob es sinnvoll wäre generelle Error Nachrichten einzurichten:
bsp: error.fetchUser

```suggestion
  "fetchUserError": "There was an Error fetching User data",
```

2023-10-27 11:10 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "components.PrivacyModal.readPrivacypolicy2": "",
Nicht ganz clean, aber ich wüsste auf die Schnelle auch keine andere Möglichkeit. ^^'

2023-10-27 11:11 UTC, juli-txt commented on src/shared/translation/translationGerman.json
> +  "User fetching error": "Es gab einen Fehler beim Abrufen der Benutzerdaten.",
```suggestion
  "fetchUserError": "Es gab einen Fehler beim Abrufen der Benutzerdaten.",
```

2023-10-27 11:12 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.hooks.tsx
> +  readonly privacyPolicyCookie: boolean
```suggestion
  readonly privacyPolicyCookie: Cookie
```

2023-10-27 11:17 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.hooks.tsx
> +  const privacyPolicyCookie = cookies['privacy_accept_token'] != null
Wenn spart sich eine logische Überprüfung, wenn man direkt den Cookie returned, um ihn in der Komponente direkt zu verwenden.

Also statt hier einen Boolean zu erzeugen, indem überprüft wird, ob der Cookie existert, um ihn dann später auf true oder false zu überprüfen, kann man auch direkt den Cookie returnen, um die Existenz des Cookies als true/false für das Rendering der Komponente verwenden.

```suggestion
```

2023-10-27 11:19 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.hooks.tsx
> + * @prop privacyPolicyCookieSet - Currently set cookie
```suggestion
 * @prop privacyPolicyCookie - The currently set cookie
```

2023-10-27 11:20 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.hooks.tsx
> + */
```suggestion
 * @category Hooks
 * @interface
 */
```

2023-10-27 11:28 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.test.tsx
> +    const link = form.getByRole('button', { name: /pages.PrivacyPolicy/i })
Könnte das fehlschlagen, wenn der Key angepasst wird?

2023-10-27 11:28 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.test.tsx
> +      name: /components.PrivacyModal.readPrivacypolicy pages.PrivacyPolicy/i
Hier vermutlich auch

2023-10-27 11:32 UTC, juli-txt commented on src/components/PrivacyModal/PrivacyModal.tsx
> +                  handleModal(false), (window.location.href = 'https://moodle.hs-kempten.de/enrol/index.php?id=357')
Ich hab gesehen, du hast das wohl schon mal zwischen href und assign hin und her geändert. Der Linter meckert bei href auch rum, da hier eine ungewollte Mutation durchgeführt wird.

2023-10-27 11:43 UTC, Platura commented on src/components/PrivacyModal/PrivacyModal.tsx
> +    <Modal
Das ist so schlimm zu lesen aber ok

2023-11-03 12:03 UTC, juli-txt requested changes

2023-11-06 12:45 UTC, juli-txt commented on src/shared/translation/translationEnglish.json
> +  "fetchUserError": "There was an Error fetching User data",
Wird glaub ich nicht mehr benötigt, nach den Änderungen von Dimi

```suggestion
```

2023-11-06 12:45 UTC, juli-txt commented on src/shared/translation/translationGerman.json
> +  "fetchUserError": "There was an Error fetching User data",
Wird ebenfalls nicht mehr benötigt, nach Änderungen von Dimi

```suggestion
```

2023-11-07 10:20 UTC, juli-txt approved these changes

2023-11-07 16:39 UTC, merged