221 technical no reloading to see questionnaire results after answering questionnaire
HASKI-RAK/HASKI-Frontend pull request #223
Opened 2023-10-17 08:19 UTC by DimitriB01

## Description

## Type of changes

- [x] Bugfix 
- [ ] Feature 
- [ ] Refactoring 
- [x] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [x] Everything build out of Material UI components
- [x] New Material UI components capsulated via dependency injection in "@common/components"
- [x] Provide basic information pieces in comments
- [x] Establish interface to backend (if necessary) 
- [x] Use Skeleton components if something has to be fetched (if necessary)
- [x] Error management: Components should handle undefined inputs
- [x] Components should be resuable (if possible)
- [x] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-10-26 14:03 UTC, theUpsider requested changes
Comments left

2023-10-26 14:03 UTC, theUpsider commented on src/components/SkeletonList/SkeletonList.tsx
>        <React.Fragment key={`MenuBar-Topic-Skeleton-${i}`}>
wozu ist das react fragment hier?

2023-10-26 14:21 UTC, DimitriB01 commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +import { SkeletonList } from '../../../index'
Benutze einen anderen Button

2023-10-26 15:00 UTC, DimitriB01 commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +              if (error.message !== 'Failed to fetch') {
Kriege nur eine Message: 
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/92084464/831561f2-cea4-4e13-b94d-6dfc4aced81e)

habe versucht im getData zu schauen ob er da reinläuft aber die console.logs lösen nicht aus 🤔 ...

2023-10-26 15:00 UTC, DimitriB01 commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +              if (error.message !== 'Failed to fetch') {
bei error.status oder error.statusCode erhalte ich nur undefined

2023-10-26 15:23 UTC, DimitriB01 commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
>  }: QuestionnaireResultsModalProps) => {
Wurde in 2 Funktionen ausgelagert. Nun zieht er die UseEffekt in die Berechnung mit ein. Soll ich da noch weiter versuchen zu vereinfachen??

2023-10-31 09:36 UTC, theUpsider commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +import { SkeletonList } from '../../../index'
Bruh but why not "import { SkeletonList } from '@components'"?

2023-10-31 09:36 UTC, theUpsider commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +import { SkeletonList } from '../../../index'
Why not "import { SkeletonList } from '@components'"?

2023-10-31 09:36 UTC, theUpsider reviewed
just small comment

2023-10-31 10:01 UTC, DimitriB01 commented on src/components/Questionnaire/QuestionnaireResults/Modal/QuestionnaireResultsModal.tsx
> +import { SkeletonList } from '../../../index'
achso darauf wolltest du hinaus

2023-10-31 10:08 UTC, theUpsider approved these changes

2023-10-31 10:09 UTC, merged