233 style cards nodes and other stuff you can find for evaluation
HASKI-RAK/HASKI-Frontend pull request #235
Opened 2023-10-31 15:24 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [ ] Feature 
- [ ] Refactoring 
- [x] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-10-31 16:06 UTC, DimitriB01 commented
Breadcrumbs without ids and redirecting to correct course or topic if clicked on
![image](https://github.com/HASKI-RAK/HASKI-Frontend/assets/92084464/0d2616d6-fc3b-40de-a4fc-893497e0d8e4)

2023-11-02 14:29 UTC, juli-txt requested changes

2023-11-06 10:37 UTC, juli-txt commented on src/components/BreadcrumbsContainer/BreadcrumbsContainer.tsx
> +const showCurrentBreadcrump = (
Hier vielleicht noch einen kurzen Kommentar (1 Zeile) einfügen, um die Funktion zu beschreiben

2023-11-06 10:49 UTC, juli-txt approved these changes

2023-11-06 10:54 UTC, merged