eval 2 rein mergen
HASKI-RAK/HASKI-Frontend pull request #292
Opened 2023-12-19 14:15 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [x] Feature 
- [x] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2023-12-19 15:31 UTC, theUpsider requested changes

2023-12-19 15:31 UTC, theUpsider commented on .github/workflows/build_eval2.yaml
Muss nicht mit auf den main. Kann auf dem branch bleiben bzw delete

2023-12-19 15:31 UTC, theUpsider commented on .github/workflows/build_ke-eval-2.yaml
Ebenso nicht auf main

2023-12-19 15:31 UTC, theUpsider commented on public/config/env.production.json
Das sollte reverted werden

2023-12-19 15:31 UTC, theUpsider commented on src/components/Footer/Footer.test.tsx
> +    expect(getByText('projectHASKI' + '™ ' + new Date().getFullYear())).toBeInTheDocument()
sind wir ein trademark?

2023-12-19 15:31 UTC, theUpsider commented on src/components/Footer/Footer.tsx
> +                {t('projectHASKI') + '™ ' + new Date().getFullYear()}
Wir sind glaub kein tm. Das könnte rechtlich problematisch sein.

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultFlag/DefaultFlag.tsx
> +import FlagIcon from '@mui/icons-material/Flag'
```suggestion
import DefaultFlag from '@mui/icons-material/Flag'
```

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultFlag/DefaultFlag.tsx
> +export { FlagIcon as Flag }
```suggestion
export { DefaultFlag as Flag }
```

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultForum/DefaultForum.tsx
> +import ForumIcon from '@mui/icons-material/Forum'
```suggestion
import DefaultForum from '@mui/icons-material/Forum'
```

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultForum/DefaultForum.tsx
> +export { ForumIcon as Forum }
```suggestion
export { DefaultForum as Forum }
```

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultSettingsApplications/DefaultSettingsApplications.ts
> +import DefaultSettingsApplicationsIcon from '@mui/icons-material/SettingsApplications'
```suggestion
import DefaultSettingsApplications from '@mui/icons-material/SettingsApplications'
```

2023-12-20 16:26 UTC, juli-txt commented on src/common/icons/DefaultSettingsApplications/DefaultSettingsApplications.ts
> +export { DefaultSettingsApplicationsIcon as SettingsApplications }
```suggestion
export { DefaultSettingsApplications as SettingsApplications }
```

2023-12-20 16:26 UTC, juli-txt commented on src/components/MenuBar/MenuBar.test.tsx
> +  test('click on Learningcharacteristic should open Questionnaire Results Modal', () => {
```suggestion
  test('click on Learning Characteristics should open Questionnaire Results Modal', () => {
```

2023-12-20 16:26 UTC, juli-txt commented on src/components/index.ts
> +export { usePrivacyModal, type PrivacyModalHookReturn } from './PrivacyModal/PrivacyModal.hooks'
```suggestion
export * from './PrivacyModal/PrivacyModal.hooks'
```

2023-12-20 16:26 UTC, juli-txt commented on src/components/index.ts
> +export { useLearningPathTopic, useLearningPathElement } from './LocalNav/LocalNav.hooks'
```suggestion
export * from './LocalNav/LocalNav.hooks'
```

2023-12-20 16:26 UTC, juli-txt commented on src/services/xAPI/Statement.test.tsx
> +      result.current.sendStatement(xAPIVerb.clicked, 'filePath').catch((error) => log.error(error))
Die Error im Tests wolltest du drin lassen?

2023-12-21 13:00 UTC, DimitriB01 commented on src/services/xAPI/Statement.test.tsx
> +      result.current.sendStatement(xAPIVerb.clicked, 'filePath').catch((error) => log.error(error))
jep, habe den catch entfernt

2024-01-15 09:43 UTC, juli-txt approved these changes

2024-01-15 10:01 UTC, merged