273 localnav should center on clicked learning element in learning path view
HASKI-RAK/HASKI-Frontend pull request #322
Opened 2024-05-21 13:48 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [x] Feature 
- [ ] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2024-05-22 08:21 UTC, DimitriB01 commented
Das hardgecodete Zeug in components/Questionnaire/OpenQuestionnaire würde ich vorschlagen zu lassen. Dann würde ich das Thema als nächstes im Backend angehen. 

Linten würde ich nach dem Approve, da hier einige Imports geändert werden würden (300+ changes)

2024-06-19 14:17 UTC, DimitriB01 commented on src/shared/translation/translationEnglish.json
>    "error.fetchLearningPathTopic": "An error occured while fetching the LearningPathTopic data.",
Vereinheitlichen

2024-06-19 14:17 UTC, DimitriB01 commented on src/shared/translation/translationGerman.json
>    "error.fetchListK": "Beim Abrufen der ListK-Fragebogendaten ist ein Fehler aufgetreten.",
Vereinheitlichen

2024-06-21 10:18 UTC, theUpsider commented on src/common/hooks/LearningPathTopicProgress/LearningPathTopicProgress.hooks.tsx
> + * @param courseId
`@param name - beschreibung`
sagt mein eslint

2024-06-21 10:24 UTC, theUpsider commented on src/common/hooks/LearningPathTopicProgress/LearningPathTopicProgress.hooks.tsx
> +                return [] as number[]
Ist unnötig
```suggestion
                return []
```

2024-06-21 10:24 UTC, theUpsider commented on src/common/hooks/LearningPathTopicProgress/LearningPathTopicProgress.hooks.tsx
> +            return [] as number[]
```suggestion
            return []
```

2024-06-21 10:25 UTC, theUpsider commented on src/pages/Topic/Topic.tsx
> +   * @param user
```suggestion
   * @param user - The user BLABLABLA
```

2024-06-21 10:47 UTC, theUpsider commented on src/pages/Course/Course.tsx
> +  const { topicProgress, isLoading, topics } = useLearningPathTopicProgress({ courseId })
```suggestion
    const { courseId } = useParams<{
    courseId: string
  }>()
```
Carsten dont cast

2024-06-21 10:49 UTC, theUpsider approved these changes

2024-06-21 10:49 UTC, theUpsider requested changes
bislle was ändern noch

2024-06-21 10:50 UTC, DimitriB01 commented on src/common/hooks/LearningPathTopicProgress/LearningPathTopicProgress.hooks.tsx
>      }, 1000)
ja, nun schon

2024-06-21 11:21 UTC, juli-txt commented on src/pages/Topic/Topic.tsx
> +   * @param user
Dokumentation und Kommentare werden aktuell vernachlässigt.

2024-06-21 11:24 UTC, juli-txt commented on src/common/hooks/LearningPathTopicProgress/LearningPathTopicProgress.hooks.tsx
> +            return [] as number[]
Also bei mir meckert er immer, weil dann eine andere Funktion den Type nicht gecheckt hat.

2024-06-24 12:39 UTC, theUpsider approved these changes

2024-06-25 10:41 UTC, merged