324 tutor can create a course in the frontend
HASKI-RAK/HASKI-Frontend pull request #340
Opened 2024-08-28 08:57 UTC by DimitriB01

## Description

## Type of changes

- [ ] Bugfix 
- [x] Feature 
- [ ] Refactoring 
- [ ] Optimization 
- [ ] Documentation 
- [ ] CI/CD 
- [ ] Other 

## Requirements
- [ ] Everything build out of Material UI components
- [ ] New Material UI components capsulated via dependency injection in "@common/components"
- [ ] Provide basic information pieces in comments
- [ ] Establish interface to backend (if necessary) 
- [ ] Use Skeleton components if something has to be fetched (if necessary)
- [ ] Error management: Components should handle undefined inputs
- [ ] Components should be resuable (if possible)
- [ ] [Component Requirements](https://lab.las3.de/nextcloud/index.php/apps/onlyoffice/510074?filePath=%2FHASKI-Extern%2F06-Frontend%2F03-UX%2F04-Implementation%2FComponent_Requirements.docx) are met

2024-10-14 15:00 UTC, theUpsider requested changes
stufffff

2024-10-16 12:30 UTC, DimitriB01 commented on src/components/AlgorithmSettingsModal/AlgorithmSettingsModal.hooks.tsx
> +  const handleSave = useCallback(() => {
Ist Kevins Komponente. Er macht einen post ans backend, wenn es erfolgreich war, dann setzt er die value im store (man spart sich nochmal einen get vom Backend)

2024-10-16 12:35 UTC, DimitriB01 commented on src/components/AlgorithmSettingsModal/AlgorithmSettingsModal.tsx
> +  const options =
Ja schon richtig verstanden, wobei die referenz value ein key ist, der in beiden translations identisch ist. (beides englisch)

2024-10-16 12:54 UTC, DimitriB01 commented on src/components/CreateCourse/Modal/CreateCourseModal.tsx
> +        university: user?.university || 'No value given',
ja stimmt das ist stupid, war noch vom anfang

2024-10-16 13:34 UTC, DimitriB01 commented on src/components/CreateCourse/Modal/CreateCourseModal.tsx
> +    const handleCreateCourse = () => {
mit callback werden die states (.id, .fullname, .university...) nicht korrekt geladen. Kommt im Backend immer empty an.

2024-10-16 13:53 UTC, DimitriB01 commented on src/components/CreateCourse/Modal/CreateCourseModal.tsx
> +        created_at: formatDate(new Date())
wurde geändert, wird automatisch im Backend gesetzt.

2024-10-16 14:16 UTC, DimitriB01 commented on src/components/CreateCourse/Table/CreateCourseDetailsTable.tsx
> +CreateCourseDetailsTable.displayName = 'CreateCourseDetailsTable'
memo hinzugefügt.

2024-10-16 14:17 UTC, DimitriB01 commented on src/components/CreateCourse/Table/CreateCourseTable.tsx
> +                borderColor: '#e0e0e0'
Diese Farbe müsste in jedem Theme genau gleich sein. Deswegen habe ich es gleich hard coded gelassen.

2024-10-18 07:56 UTC, DimitriB01 commented on src/components/CreateTopic/Modal/CreateTopicModal.tsx
> +      setSelectedTopics((prevSelectedTopics) => [...prevSelectedTopics].sort((a, b) => a.topic_lms_id - b.topic_lms_id))
is ausgelagert in handleTopicChange

2024-10-31 09:53 UTC, DimitriB01 commented on src/components/CreateTopic/Modal/CreateTopicModal.tsx
> +            {activeStep === 0 ? (
done

2024-10-31 10:19 UTC, DimitriB01 commented on src/components/CreateTopic/Modal/CreateTopicModal.tsx
> +                  addSnackbar({
Ich habe in eine componente in /Snackbar/HandleError.tsx reingetan. Man könnte eigentlich für alle componenten übergreifend diesen HandleError nutzen.

2024-10-31 11:49 UTC, DimitriB01 commented on src/components/CreateTopic/Table/CreateAlgorithmTable.tsx
> +        if (!selectedAlgorithms[lmsTopic.topic_lms_id]) {
selectedAlgorithms aus dependency entfernt

2024-10-31 12:10 UTC, DimitriB01 commented on src/components/CreateTopic/Table/CreateAlgorithmTable.tsx
> +  selectedAlgorithms: { [key: number]: CreateAlgorithmTableNameProps[] }
you are right

2024-11-22 07:27 UTC, closed without merging